-- MySQL Script generated by MySQL Workbench
-- Sat Oct 28 16:10:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema data_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema data_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data_test` DEFAULT CHARACTER SET utf8 ;
USE `data_test` ;

-- -----------------------------------------------------
-- Table `data_test`.`resellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_test`.`resellers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Last_active` DATETIME NULL,
  `Email` VARCHAR(45) NOT NULL,
  `AOV` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_test`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_test`.`stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resellers_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `SKU` INT NOT NULL,
  `Price` FLOAT NOT NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stock_resellers_idx` (`resellers_id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_resellers`
    FOREIGN KEY (`resellers_id`)
    REFERENCES `data_test`.`resellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_test`.`reseller_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_test`.`reseller_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resellers_id` INT NOT NULL,
  `Order` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Status` VARCHAR(45) NULL,
  `Error` VARCHAR(45) NULL,
  `Total` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tabreseller_orders_resellers1_idx` (`resellers_id` ASC) VISIBLE,
  CONSTRAINT `fk_tabreseller_orders_resellers1`
    FOREIGN KEY (`resellers_id`)
    REFERENCES `data_test`.`resellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_test`.`billing_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_test`.`billing_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resellers_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Company` VARCHAR(45) NULL,
  `Street_address` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Region` VARCHAR(45) NOT NULL,
  `Postal_code` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_billing_address_resellers1_idx` (`resellers_id` ASC) VISIBLE,
  CONSTRAINT `fk_billing_address_resellers1`
    FOREIGN KEY (`resellers_id`)
    REFERENCES `data_test`.`resellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_test`.`shipping_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_test`.`shipping_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resellers_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Company` VARCHAR(45) NULL,
  `Street_address` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Region` VARCHAR(45) NOT NULL,
  `Postal_code` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shipping_address_resellers1_idx` (`resellers_id` ASC) VISIBLE,
  CONSTRAINT `fk_shipping_address_resellers1`
    FOREIGN KEY (`resellers_id`)
    REFERENCES `data_test`.`resellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_test`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_test`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resellers_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Date_registered` DATE NULL,
  `Orders` VARCHAR(45) NULL,
  `Total_spent` FLOAT NULL,
  `AOV` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_resellers1_idx` (`resellers_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_resellers1`
    FOREIGN KEY (`resellers_id`)
    REFERENCES `data_test`.`resellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_test`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_test`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clients_id` INT NOT NULL,
  `orders` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Status` VARCHAR(45) NULL,
  `Error` VARCHAR(45) NULL,
  `Total` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_clients1_idx` (`clients_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `data_test`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_test`.`login_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_test`.`login_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clients_id` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Email_address` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_login_details_clients1_idx` (`clients_id` ASC) VISIBLE,
  CONSTRAINT `fk_login_details_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `data_test`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_test`.`clients_billing_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_test`.`clients_billing_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clients_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Company` VARCHAR(45) NULL,
  `Street_address` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Region` VARCHAR(45) NOT NULL,
  `Postal_code` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_billing_address_clients1_idx` (`clients_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_billing_address_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `data_test`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_test`.`clients_shipping_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_test`.`clients_shipping_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clients_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Company` VARCHAR(45) NULL,
  `Street_address` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Region` VARCHAR(45) NOT NULL,
  `Postal_code` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_shipping_address_clients1_idx` (`clients_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_shipping_address_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `data_test`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
